# Generated by Django 5.1.3 on 2025-03-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_pricerange_alter_restaurants_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurants',
            options={'managed': False},
        ),
    ]
