# Generated by Django 5.1.3 on 2025-03-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurants_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
