# Generated by Django 5.1.3 on 2025-03-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_delete_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceRange',
        ),
    ]
